--- 
before_install: 
  - "docker build -t my-frontend -f Dockerfile.dev ."
deploy: 
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  app: docker-test
  bucket_name: elasticbeanstalk-ap-south-1-291779423517
  env: DockerTest-env
  provider: elasticbeanstalk
  region: ap-south-1
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  true: 
    branch: master
script: 
  - "docker run my-frontend npm run test -- --coverage"
services: 
  - docker
sudo: required
